version: '3'

services:
  postgres:
    image: postgres:11.5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - db
    ports:
      - 5432:5432
  keycloak:
    image: jboss/keycloak:latest
    environment:
      DB_PORT: 5432
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    networks:
      - db
    ports:
      - 8080:8080
      - 8543:8543
      - 10090:10090
    depends_on:
      - postgres
    healthcheck:
      test: "exit 0"
networks:
  db:
    driver: bridge
volumes:
  postgres_data:
    driver: local
