version: '3'

services:
  database:
    image: postgres:11.5
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - "5432"
    ports:
      - 8000:5432
    volumes:
      - ./services/database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./services/database/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql
  pgadmin:
      image: dpage/pgadmin4
      ports:
        - 5454:5454/tcp
      environment:
        - PGADMIN_DEFAULT_EMAIL=admin@mydomain.com
        - PGADMIN_DEFAULT_PASSWORD=admin
        - PGADMIN_LISTEN_PORT=5454